pipeline {
    agent any

    stages {
        stage("Checkout") {
            steps {
                checkout scm
                sh '''
                  ls
                '''
            }
        }

        stage("Build and start test image") {
            steps {
                sh '''
                  pwd
                  java -version
                '''
            }
        }
    }
}